version: "3"
services:
  node:
    image: "node:9.10.1"
    user: "node"
    container_name: 'cv'
    working_dir: /home/node/app/my-cv
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:3000"
    tty: true
    command: "npm start"
    # command: "cd /home/node/app/my-cv;yarn start"